# automatically generated by the FlatBuffers compiler, do not modify

# namespace: io

class OpCode(object):
    BITWISE_NOT = 0
    BITWISE_AND = 1
    BITWISE_OR = 2
    BITWISE_XOR = 4
    BITWISE_K_OF_N = 5
    BITWISE_NAND = 9
    BITWISE_NOR = 10
    BITWISE_XNOR = 12
    BITMASK_ZEROS = 16
    BITMASK_ONES = 17
    BITWISE_CONV_ND = 32
    BITWISE_CONV_1D = 33
    BITWISE_CONV_2D = 34
    BITWISE_FFT_ND = 64
    BITWISE_FFT_1D = 65
    BITWISE_FFT_2D = 66
    LOGICAL_NOT = 128
    LOGICAL_AND = 129
    LOGICAL_OR = 130
    LOGICAL_XOR = 132
    LOGICAL_NAND = 137
    LOGICAL_NOR = 138
    LOGICAL_XNOR = 140
    RESHAPE = 160
    MC_EXPECT_VAL = 240
    MC_VAR_LOSS = 241
    MC_SAMPLER = 242
