# automatically generated by the FlatBuffers compiler, do not modify

# namespace: io

class OperatorArgs(object):
    NONE = 0
    KofNArgs = 1
    ReshapeArgs = 2
    MonteCarloExpectedValueOptions = 3
