# automatically generated by the FlatBuffers compiler, do not modify

# namespace: io

class TensorType(object):
    UINT32 = 0
    UINT4 = 4
    UINT8 = 8
    UINT16 = 16
    UINT64 = 64
    FLOAT16 = 144
    FLOAT32 = 160
    FLOAT64 = 192
