from __future__ import annotations

import flatbuffers

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class KofNArgs(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> KofNArgs: ...
  @classmethod
  def GetRootAsKofNArgs(cls, buf: bytes, offset: int) -> KofNArgs: ...
  @classmethod
  def KofNArgsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Atleast(self) -> int: ...
def KofNArgsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def KofNArgsAddAtleast(builder: flatbuffers.Builder, atleast: int) -> None: ...
def KofNArgsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

