# automatically generated by the FlatBuffers compiler, do not modify

# namespace: io

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MonteCarloExpectedValueOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MonteCarloExpectedValueOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMonteCarloExpectedValueOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MonteCarloExpectedValueOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x50\x59\x31", size_prefixed=size_prefixed)

    # MonteCarloExpectedValueOptions
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MonteCarloExpectedValueOptions
    def CiLow(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.05

    # MonteCarloExpectedValueOptions
    def CiHigh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.95

def MonteCarloExpectedValueOptionsStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    MonteCarloExpectedValueOptionsStart(builder)

def MonteCarloExpectedValueOptionsAddCiLow(builder: flatbuffers.Builder, ciLow: float):
    builder.PrependFloat32Slot(0, ciLow, 0.05)

def AddCiLow(builder: flatbuffers.Builder, ciLow: float):
    MonteCarloExpectedValueOptionsAddCiLow(builder, ciLow)

def MonteCarloExpectedValueOptionsAddCiHigh(builder: flatbuffers.Builder, ciHigh: float):
    builder.PrependFloat32Slot(1, ciHigh, 0.95)

def AddCiHigh(builder: flatbuffers.Builder, ciHigh: float):
    MonteCarloExpectedValueOptionsAddCiHigh(builder, ciHigh)

def MonteCarloExpectedValueOptionsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MonteCarloExpectedValueOptionsEnd(builder)
