from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ReshapeArgs(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ReshapeArgs: ...
  @classmethod
  def GetRootAsReshapeArgs(cls, buf: bytes, offset: int) -> ReshapeArgs: ...
  @classmethod
  def ReshapeArgsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def NewShape(self, i: int) -> typing.List[int]: ...
  def NewShapeAsNumpy(self) -> np.ndarray: ...
  def NewShapeLength(self) -> int: ...
  def NewShapeIsNone(self) -> bool: ...
def ReshapeArgsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ReshapeArgsAddNewShape(builder: flatbuffers.Builder, newShape: uoffset) -> None: ...
def ReshapeArgsStartNewShapeVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartNewShapeVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ReshapeArgsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

